import Pkg

Pkg.add("JuliaFormatter")
Pkg.add("HypothesisTests")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("ArgParse")
Pkg.add("PackageCompiler")
Pkg.add("Plots")
Pkg.add("StatsBase")
Pkg.add("Distributions")
Pkg.add("TimeSeries")
Pkg.add("GLM")
Pkg.add("MixedModels")
Pkg.add("StatsFuns")
Pkg.add("StatsModels")
Pkg.add("Distances")
Pkg.add("Clustering")
Pkg.add("KernelDensity")
Pkg.add("MultivariateStats")
Pkg.add("Survival")
Pkg.add("BenchmarkTools")